export const courseSeeds = [
  {
    id: "ai",
    title: "Ứng dụng AI vào công việc hằng ngày",
    category: "AI & Dữ liệu",
    description: "Học cách giao việc cho AI, kiểm chứng kết quả và xây dựng quy trình tự động hóa cá nhân.",
    teacher: "Bảo Trâm",
    duration: "2 giờ 15 phút",
    level: "Cơ bản",
    color: "lavender",
    icon: "Sparkles",
    label: "AI IN PRACTICE",
    students: 28,
    scope: "Toàn MatureX",
    lessons: [
      "Hiểu đúng năng lực và giới hạn của AI",
      "Kỹ thuật tạo ngữ cảnh và cấu trúc prompt",
      "Xây dựng trợ lý cho một nhiệm vụ cụ thể",
      "Kiểm tra và chuẩn hóa kết quả",
    ],
    skill: "prompting",
    status: "published",
  },
  {
    id: "culture",
    title: "Nền tảng văn hoá và nguyên tắc làm việc",
    category: "Văn hoá MatureX",
    description: "Bộ nguyên tắc cốt lõi giúp các thành viên cùng chung nhịp điệu, minh bạch và tự chủ.",
    teacher: "Đức An",
    duration: "1 giờ 45 phút",
    level: "Nhập môn",
    color: "peach",
    icon: "Compass",
    label: "ONE MATUREX",
    students: 45,
    scope: "Toàn MatureX",
    lessons: [
      "Tại sao chúng ta ở đây",
      "Tính trung thực trí tuệ trong công việc",
      "Định nghĩa xong một việc",
      "Giao tiếp chủ động và phản hồi thẳng thắn",
    ],
    skill: "responsibility",
    status: "published",
  },
  {
    id: "thinking",
    title: "Tư duy phản biện và giải quyết vấn đề",
    category: "Tư duy",
    description: "Tách nhỏ vấn đề phức tạp, truy vết nguyên nhân gốc rễ và đưa ra giải pháp dựa trên bằng chứng.",
    teacher: "Ngọc Linh",
    duration: "3 giờ",
    level: "Nâng cao",
    color: "blue",
    icon: "Target",
    label: "CRITICAL THINKING",
    students: 19,
    scope: "Toàn MatureX",
    lessons: [
      "Bóc tách vấn đề bằng cây câu hỏi",
      "Phân biệt triệu chứng và nguyên nhân",
      "Kiểm tra tính hợp lý của dữ liệu",
      "Viết đề xuất giải pháp khả thi",
    ],
    skill: "thinking",
    status: "published",
  },
];

export const skillSeeds = [
  {
    id: "prompting",
    name: "Kỹ năng làm việc cùng AI",
    category: "AI & Dữ liệu",
    target: 4,
    current: 3,
    description: "Khả năng đưa ngữ cảnh, tạo prompt chuẩn xác và kiểm chứng dữ liệu sinh ra bởi mô hình ngôn ngữ.",
  },
  {
    id: "responsibility",
    name: "Trách nhiệm và cam kết",
    category: "Văn hoá",
    target: 5,
    current: 4,
    description: "Làm chủ mục tiêu, giao tiếp minh bạch khi có sai lệch và kiên định với chất lượng bàn giao.",
  },
  {
    id: "thinking",
    name: "Tư duy phân tích và giải quyết vấn đề",
    category: "Năng lực cốt lõi",
    target: 4,
    current: 2,
    description: "Tách vấn đề phức tạp, đối chiếu bằng chứng khách quan và xây dựng giải pháp có căn cứ.",
  },
];

export const assignmentSeeds = [
  {
    id: "asg-1",
    title: "Thiết kế một prompt hoàn chỉnh cho công việc thực tế",
    courseId: "ai",
    type: "Thực hành",
    due: "15/09/2026",
    status: "todo",
    rubric: ["Rõ mục tiêu", "Có giới hạn", "Có kiểm chứng"],
    body: "",
    person: "me",
    history: [],
  },
  {
    id: "asg-2",
    title: "Tự đánh giá theo nguyên tắc văn hoá MatureX",
    courseId: "culture",
    type: "Tự chiêm nghiệm",
    due: "20/09/2026",
    status: "submitted",
    rubric: ["Thành thật", "Rõ ràng", "Hành động cụ thể"],
    body: "Bản tự đánh giá quý 3...",
    person: "me",
    history: [],
  },
];
