export const categories = [
  "Tất cả",
  "AI & Dữ liệu",
  "Văn hoá MatureX",
  "Tư duy",
  "Chuyên môn",
  "Lãnh đạo",
  "Company Builder",
];
export const people = [
  {
    id: "me",
    name: "Minh Anh",
    initials: "MA",
    job: "Product Researcher",
    team: "Thedeerly",
    color: "lavender",
    progress: 68,
  },
  {
    id: "p2",
    name: "Hoàng Nam",
    initials: "HN",
    job: "Creative Designer",
    team: "Thedeerly",
    color: "peach",
    progress: 82,
  },
  {
    id: "p3",
    name: "Thu Hà",
    initials: "TH",
    job: "Marketing Executive",
    team: "EcomCreate",
    color: "green",
    progress: 45,
  },
  {
    id: "p4",
    name: "Quang Huy",
    initials: "QH",
    job: "Operations Specialist",
    team: "Timond.de",
    color: "blue",
    progress: 76,
  },
  {
    id: "p5",
    name: "Ngọc Linh",
    initials: "NL",
    job: "Learning Designer",
    team: "MatureX",
    color: "pink",
    progress: 92,
  },
  {
    id: "p6",
    name: "Đức An",
    initials: "ĐA",
    job: "Team Lead",
    team: "Microm",
    color: "sand",
    progress: 60,
  },
];
export const courseSeeds = [
  {
    id: "ai",
    title: "Làm việc cùng AI: từ câu hỏi đến kết quả",
    category: "AI & Dữ liệu",
    description:
      "Biến AI thành người cộng sự. Học cách giao việc rõ ràng, kiểm chứng đầu ra và ứng dụng vào công việc mỗi ngày.",
    teacher: "Ngọc Linh",
    duration: "2 giờ 20 phút",
    level: "Nền tảng",
    color: "lavender",
    icon: "Sparkles",
    label: "AI IN PRACTICE",
    students: 24,
    scope: "Toàn MatureX",
    lessons: [
      "AI trong công việc tại MatureX",
      "Viết đề bài rõ ràng cho AI",
      "Kiểm chứng: đừng dừng ở câu trả lời",
      "Thực hành nghiên cứu khách hàng",
    ],
    skill: "ai",
    status: "published",
  },
  {
    id: "culture",
    title: "MatureX & hành trình trưởng thành",
    category: "Văn hoá MatureX",
    description:
      "Hiểu môi trường MatureX, cách phối hợp và thực hành trách nhiệm qua những tình huống gần gũi.",
    teacher: "Đức An",
    duration: "1 giờ 30 phút",
    level: "Nền tảng",
    color: "green",
    icon: "Sprout",
    label: "GROW TOGETHER",
    students: 36,
    scope: "Toàn MatureX",
    lessons: [
      "Môi trường để cùng phát triển",
      "Làm rõ trách nhiệm và cam kết",
      "Phản hồi để cùng tốt hơn",
      "Học từ một điều chưa như ý",
    ],
    skill: "responsibility",
    status: "published",
  },
  {
    id: "research",
    title: "Thấu hiểu khách hàng bằng bằng chứng",
    category: "Chuyên môn",
    description:
      "Từ tín hiệu nhu cầu đến giả thuyết sản phẩm. Tạo nghiên cứu có nguồn và đủ rõ để ra quyết định.",
    teacher: "Ngọc Linh",
    duration: "3 giờ 10 phút",
    level: "Ứng dụng",
    color: "peach",
    icon: "ScanSearch",
    label: "CUSTOMER FIRST",
    students: 18,
    scope: "EcomCreate",
    lessons: [
      "Bắt đầu từ vấn đề khách hàng",
      "Tìm và đánh giá nguồn",
      "Từ quan sát đến giả thuyết",
      "Thiết kế thử nghiệm nhỏ",
    ],
    skill: "research",
    status: "published",
  },
  {
    id: "thinking",
    title: "Tư duy phản biện trong công việc",
    category: "Tư duy",
    description:
      "Nhìn rõ điều đã biết, điều đang giả định và câu hỏi cần trả lời trước khi quyết định.",
    teacher: "Đức An",
    duration: "1 giờ 45 phút",
    level: "Nền tảng",
    color: "blue",
    icon: "Brain",
    label: "THINK CLEARLY",
    students: 28,
    scope: "Toàn MatureX",
    lessons: [
      "Dữ kiện hay suy luận?",
      "Đặt câu hỏi đúng",
      "Kiểm tra giả định",
      "Ra quyết định có căn cứ",
    ],
    skill: "thinking",
    status: "published",
  },
  {
    id: "lead",
    title: "Coaching: giúp đội ngũ tự làm được",
    category: "Lãnh đạo",
    description:
      "Giao việc có mục tiêu, hỏi để mở ra góc nhìn và phản hồi dựa trên bằng chứng.",
    teacher: "Đức An",
    duration: "2 giờ 40 phút",
    level: "Nâng cao",
    color: "pink",
    icon: "Users",
    label: "LEAD WITH CARE",
    students: 12,
    scope: "Toàn MatureX",
    lessons: [
      "Vai trò của người hướng dẫn",
      "Giao việc và giới hạn",
      "Một cuộc trò chuyện coaching",
      "Chuyển giao để tăng tự chủ",
    ],
    skill: "coaching",
    status: "published",
  },
  {
    id: "builder",
    title: "Từ giả thuyết đến thử nghiệm kinh doanh",
    category: "Company Builder",
    description:
      "Định nghĩa giả thuyết, giới hạn nguồn lực, bằng chứng cần thu và điều kiện dừng.",
    teacher: "Đức An",
    duration: "3 giờ",
    level: "Ứng dụng",
    color: "sand",
    icon: "Lightbulb",
    label: "BUILD WITH EVIDENCE",
    students: 16,
    scope: "Toàn MatureX",
    lessons: [
      "Vấn đề đáng giải quyết",
      "Thiết kế thử nghiệm",
      "Đọc bằng chứng",
      "Dừng, học và chuyển giao",
    ],
    skill: "experiment",
    status: "published",
  },
  {
    id: "ops",
    title: "Xử lý ngoại lệ trong vận hành",
    category: "Chuyên môn",
    description:
      "Nhận diện sai lệch, giữ bằng chứng và phối hợp giải quyết đến khi có kết quả xác minh.",
    teacher: "Ngọc Linh",
    duration: "1 giờ 50 phút",
    level: "Ứng dụng",
    color: "green",
    icon: "Workflow",
    label: "BETTER EVERY DAY",
    students: 14,
    scope: "Microm",
    lessons: [
      "Nhận diện một ngoại lệ",
      "Bằng chứng và người phụ trách",
      "Phối hợp xử lý",
      "Kiểm tra trước khi đóng",
    ],
    skill: "responsibility",
    status: "published",
  },
  {
    id: "data",
    title: "Đọc dữ liệu để ra quyết định tốt hơn",
    category: "AI & Dữ liệu",
    description:
      "Đọc chỉ số trong bối cảnh và xây báo cáo giúp người nhận biết việc cần làm.",
    teacher: "Ngọc Linh",
    duration: "2 giờ",
    level: "Ứng dụng",
    color: "blue",
    icon: "ChartNoAxesCombined",
    label: "DATA TO DECISIONS",
    students: 20,
    scope: "Toàn MatureX",
    lessons: [
      "Bắt đầu từ câu hỏi",
      "Kiểm tra chất lượng dữ liệu",
      "Nhìn ra sai lệch",
      "Viết khuyến nghị",
    ],
    skill: "thinking",
    status: "published",
  },
];
export const paths = [
  {
    id: "path-ai",
    title: "AI trong công việc hằng ngày",
    description:
      "Xây nền tảng, luyện tư duy và đưa AI vào một nhiệm vụ thực tế.",
    courses: ["ai", "thinking", "research"],
    color: "lavender",
    icon: "Sparkles",
    weeks: "4 tuần",
    target: "Ứng dụng AI có kiểm chứng",
  },
  {
    id: "path-new",
    title: "Chào mừng đến với MatureX",
    description:
      "Hiểu môi trường, cách làm việc và sẵn sàng cho nhiệm vụ đầu tiên.",
    courses: ["culture", "thinking", "ai"],
    color: "green",
    icon: "Sprout",
    weeks: "3 tuần",
    target: "Hội nhập và phối hợp hiệu quả",
  },
  {
    id: "path-lead",
    title: "Từ chuyên môn đến dẫn dắt",
    description:
      "Phát triển khả năng coaching, giao việc và thử nghiệm có trách nhiệm.",
    courses: ["lead", "builder", "ops"],
    color: "peach",
    icon: "Compass",
    weeks: "6 tuần",
    target: "Dẫn dắt một nhiệm vụ có phạm vi",
  },
];
export const skillSeeds = [
  {
    id: "ai",
    name: "Làm việc cùng AI",
    group: "AI & Dữ liệu",
    level: 2,
    target: 3,
    color: "lavender",
  },
  {
    id: "research",
    name: "Nghiên cứu khách hàng",
    group: "Chuyên môn",
    level: 1,
    target: 3,
    color: "peach",
  },
  {
    id: "thinking",
    name: "Tư duy phản biện",
    group: "Tư duy",
    level: 2,
    target: 3,
    color: "blue",
  },
  {
    id: "responsibility",
    name: "Thực hành trách nhiệm",
    group: "Văn hoá MatureX",
    level: 3,
    target: 3,
    color: "green",
  },
  {
    id: "coaching",
    name: "Coaching & phản hồi",
    group: "Lãnh đạo",
    level: 0,
    target: 2,
    color: "pink",
  },
  {
    id: "experiment",
    name: "Thiết kế thử nghiệm",
    group: "Company Builder",
    level: 1,
    target: 2,
    color: "sand",
  },
];
export const levels = [
  "Chưa đánh giá",
  "Hiểu",
  "Làm có hướng dẫn",
  "Làm độc lập",
  "Hướng dẫn & cải tiến",
];
export const assignmentSeeds = [
  {
    id: "a1",
    course: "ai",
    title: "Viết brief nghiên cứu khách hàng với AI",
    description:
      "Chọn một vấn đề khách hàng trong dự án của bạn. Viết đề bài cho AI, thu thập ít nhất 3 nguồn, phân biệt dữ kiện với suy luận và đề xuất một giả thuyết có thể kiểm chứng.",
    due: "11/09/2026",
    type: "Sản phẩm thực hành",
    skill: "ai",
    person: "me",
    status: "todo",
  },
  {
    id: "a2",
    course: "research",
    title: "Từ 3 quan sát đến một giả thuyết",
    description:
      "Nộp ba quan sát có nguồn, giải thích giới hạn của dữ liệu và xây một thử nghiệm nhỏ với điều kiện dừng rõ ràng.",
    due: "15/09/2026",
    type: "Áp dụng công việc",
    skill: "research",
    person: "me",
    status: "todo",
  },
  {
    id: "a3",
    course: "culture",
    title: "Một cam kết, một bài học",
    description:
      "Chia sẻ tình huống đã làm rõ trách nhiệm, điều bạn thực hiện và điều sẽ cải thiện.",
    due: "07/09/2026",
    type: "Phản tư",
    skill: "responsibility",
    person: "me",
    status: "approved",
    body: "Tôi đã xác nhận lại phạm vi và thời hạn với người phối hợp, báo sớm một sai lệch và cùng điều chỉnh cách thực hiện.",
    feedback:
      "Bài phản tư rõ bối cảnh và hành động. Tiếp tục thực hành báo sai lệch sớm và đối chiếu kết quả.",
    scores: [4, 4, 3],
    attempt: 1,
  },
  {
    id: "a4",
    course: "ai",
    title: "Kiểm chứng bản nháp do AI tạo",
    description:
      "Đánh giá một bản nháp của AI theo nguồn, tính phù hợp và khả năng áp dụng.",
    due: "10/09/2026",
    type: "Sản phẩm thực hành",
    skill: "ai",
    person: "p2",
    status: "submitted",
    body: "Tôi đối chiếu 3 nguồn, phát hiện 2 nhận định thiếu bằng chứng và sửa lại brief. Sản phẩm cuối có ghi rõ giả định cần kiểm chứng.",
    attempt: 1,
  },
  {
    id: "a5",
    course: "research",
    title: "Phân tích tín hiệu nhu cầu",
    description:
      "Tổng hợp tín hiệu khách hàng và ghi lại mức độ chắc chắn của từng nhận định.",
    due: "12/09/2026",
    type: "Áp dụng công việc",
    skill: "research",
    person: "p3",
    status: "submitted",
    body: "Báo cáo tổng hợp ba nhóm tín hiệu từ phản hồi khách hàng. Tôi đề xuất kiểm chứng thêm bằng phỏng vấn và một thử nghiệm có phạm vi nhỏ.",
    attempt: 1,
  },
];
export const eventSeeds = [
  {
    id: "e1",
    day: 10,
    month: 9,
    title: "AI thực hành: từ brief đến sản phẩm",
    time: "14:00 – 15:30",
    teacher: "Ngọc Linh",
    type: "Workshop",
    color: "lavender",
    registered: true,
  },
  {
    id: "e2",
    day: 11,
    month: 9,
    title: "Office hours · Giải đáp bài nghiên cứu",
    time: "10:00 – 11:00",
    teacher: "Ngọc Linh",
    type: "Mentoring",
    color: "peach",
    registered: false,
  },
  {
    id: "e3",
    day: 15,
    month: 9,
    title: "Học từ sai lệch, cùng nhau tiến bộ",
    time: "15:00 – 16:00",
    teacher: "Đức An",
    type: "Chia sẻ",
    color: "green",
    registered: false,
  },
  {
    id: "e4",
    day: 18,
    month: 9,
    title: "Coaching clinic cho team lead",
    time: "09:00 – 10:30",
    teacher: "Đức An",
    type: "Workshop",
    color: "pink",
    registered: false,
  },
];
export const rubric = [
  "Rõ vấn đề và mục tiêu",
  "Có nguồn và kiểm chứng",
  "Khả năng áp dụng thực tế",
];
export const normalize = (text) =>
  String(text)
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/đ/g, "d")
    .replace(/Đ/g, "D")
    .toLowerCase();
export function initialState() {
  return {
    version: 1,
    courses: structuredClone(courseSeeds),
    enrolled: ["ai", "culture", "research"],
    completed: { ai: [0, 1], culture: [0, 1, 2, 3], research: [0] },
    assignments: structuredClone(assignmentSeeds),
    skills: structuredClone(skillSeeds),
    events: structuredClone(eventSeeds),
    bookmarks: ["research"],
    notes: {},
    pathAssignments: [],
    notifications: [
      {
        id: "n1",
        text: "Mentor đã phản hồi bài “Một cam kết, một bài học”.",
        route: "assignments",
        read: false,
      },
      {
        id: "n2",
        text: "Workshop AI thực hành diễn ra ngày 10/09, lúc 14:00.",
        route: "calendar",
        read: false,
      },
    ],
    posts: [
      {
        id: "post1",
        person: "p5",
        title: "Một câu hỏi tốt có thể thay đổi cả bản brief",
        body: "Trước khi đưa đề bài cho AI, hãy thử trả lời: sản phẩm này giúp ai ra quyết định gì? Mọi người có câu hỏi nào thường dùng để làm rõ đề bài không?",
        topic: "AI & Dữ liệu",
        likes: 8,
        liked: false,
        replies: [],
      },
      {
        id: "post2",
        person: "p6",
        title: "Học từ một việc chưa như ý",
        body: "Một thử nghiệm không đạt kỳ vọng vẫn có thể mang lại bài học tốt. Tuần này, hãy chọn một giả định của mình và đối chiếu lại với bằng chứng.",
        topic: "Văn hoá MatureX",
        likes: 12,
        liked: false,
        replies: [
          {
            name: "Minh Anh",
            body: "Em sẽ thử ghi rõ điều kiện dừng trước khi bắt đầu thử nghiệm tiếp theo.",
          },
        ],
      },
    ],
    settings: {
      weekly: true,
      assignment: true,
      reminder: true,
      privateNotes: true,
    },
    evidence: [],
    quizPassed: {},
  };
}
